language: java
jdk:
- oraclejdk7
- openjdk7
- openjdk6
before_install:
- wget https://raw.github.com/josephd/ForgeTravis/1.7.2/forgeTravis.sh
- chmod +x forgeTravis.sh
install:
- "./forgeTravis.sh setup"
env:
  global:
  - TERM=dumb
  - MOD_VERSION=1.0
  - MOD_NAME=warpbook
  - MOD_NAMESPACE=panicnot42
  - MOD_JARNAME=warp-book
  - secure: ZY/tOxF7igHTgUn+F2vkA9gk3oVgqYiO7Fir5W0Lw5p92i/lmoOd7VWB2MZ6PapQXYAo0I3FWfW6GCH55mNBNsQ0jqzhC6w1kc9ArCXVc8QHmW//5AEbnGAAeuIxbAogGy1VjBqb7C/p+Ri4ioJy9L436FW8ftN55oYHEWAFvyQ=
  - secure: Q9hWaQPdIKPOrRb0R2+x9yzipCtZdMGv3FyAyWLRJRME+KdnXiveL4HDElA0UxSte61OyIMzFTnQokOHRYX74aEkv/A5a/FP4MRTDnTqI8XfrBV1yWWALIcZxjK+QAP3rWovId7pio6GiLZuKINYSBL4ZnQptQeeBxmFbwmPNtI=
  - secure: GQ+9LtqOgZCXGxkKeUwNZi7SqV+DB0LA0HCu5FkbDmEkA+3BUwC6arzsPEePbFQ33mklIVULytdVCIi06pco0SFRh6Ugweru8wQGBIj1coUcTAjUzQy6xEbXaJe/EhBq9hWjEm2dt3avC+0ivGtK33RsTjgnmqoXyykH9YbKmPw=
  matrix:
  - forge_release=latest
  - forge_release=recommended
script:
- gradle build
after_success:
- "./forgeTravis.sh release"
